# Generated by Django 4.2.5 on 2023-09-12 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=128)),
                ('class_credit', models.IntegerField()),
                ('class_year', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('teacher', models.CharField(max_length=255)),
                ('on_register', models.BooleanField(default=False)),
                ('class_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.category')),
            ],
        ),
    ]
